### PR TITLE
Convert to Endpoints, add provides and peers

### PR DESCRIPTION
**Pull request by johnsca**

### CODE REVIEW

**Comment by sebastienpattyn93** [comment]
@johnsca  are there any plans to get this upstream?

**Comment by johnsca** [comment]
That was the plan, but I ended up not needing it after all at the time of writing, and it hasn't gotten any attention in the meantime.  Do you have a use-case for the interface that you'd be willing to give it a quick test and review with?

**Comment by sebastienpattyn93** [comment]
@johnsca I have a use-case where I'm using the juju-info interface to just retrieve the ip-address off 3 units that are connected to my charm. But I was not able to get all the Ip-address. I only saw the ip of the last unit that joined. 

```python
@hook('info-relation-joined')
def info_changed(info):
    for work in info.conversations():
        print(work.get_remote('private-address'))
```

**Comment by johnsca** [comment]
Inside a specific relation hook context, the list of conversations would only contain that unit.  That was one of the issues with the RelationBase approach that Endpoints are meant to address, so the refactor definitely would address this.  However, this PR doesn't include an accessor to get the private addresses, only a deprecated copy of the existing one for the single address.  I will add one to this PR with docs to show how to use it.

**Comment by sebastienpattyn93** [comment]
That would be great!

**Comment by johnsca** [comment]
@sebastienpattyn93 Please take a look at the updated PR and at https://github.com/juju-solutions/interface-juju-info/blob/convert-endpoints/README.md

**Comment by sebastienpattyn93** [comment]
@johnsca This is amazing! this will fix the issues I had before. Thanks for the updated docs as well

**Comment by johnsca** [comment]
I'll consider that a +1, then.  :)

**Comment by sebastienpattyn93** [comment]
@johnsca  I did some more testing today and I came across an issue. I noticed since the provides side is never setting any data, or an ingress-address. the data in the relation will always be `None` and this is resulting in the fact that a` relatedUnit` from `all_joined_units` will not have the attribute `received_raw`. that is why the following is not working:

```Python
host = endpoint_from_flag('host-system.connected')
for address in host.addresses:
    print(address)
```

**Comment by sebastienpattyn93** [comment]
@johnsca  I added some prints to have a look and appearantly creating the list in a short way and then trying to use the `sorted` method is causing the issue because you receive a `generator object JujuInfoClient.addresses.<locals>.<genexpr>` instead of the ingress-address.

`line 54 of requires.py`
```Python
for adr in self.all_joined_units:
    print(adr.received_raw['ingress-address'])
print(u.recieved_raw['ingress-address'] for u in self.all_joined_units)
```

`output`
```Shell
252.254.64.1
<generator object JujuInfoClient.addresses.<locals>.<genexpr> at 0x7fa4938feca8>

```

**Pull request merged**
