### PR TITLE
Update the README for better documented example usage of the interface

### PR DESCRIPTION
**Pull request by lazypower**

### CODE REVIEW

**Comment by lazypower** [comment]
Additional information: 

> Furthermore, the juju-info interface layer just lists {{name}} in the readme, assuming the reader knows exactly which magic string should be placed there. This is one of the most opaque and confusing barriers to using reactive relations, and needs tooling and documentation to guide new users.

**Comment by kwmonroe** [comment]
Nice @chuckbutler!  LGTM

**Comment by paulgear** [comment]
Presumably "conneted" should read "connected"?

**Comment by lazypower** [comment]
addressed in #4, thanks @paulgear

**Pull request merged**
